backend:
  name: git-gateway
  branch: master

media_folder: content/assets/img
public_folder: /img

collections: 
- label: "Comedy Albums"
  name: "albums"
  folder: "markdown/albums"
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "thumbnail", name: "thumbnail", widget: "image"}

- label: "Trusted Partners"
  name: "trusted"
  folder: "markdown/trusted"
  create: true
  fields:
    - {label: "Name", name: "name", widget: "string"}
    - {label: "thumbnail", name: "thumbnail", widget: "image"}

- label: "Portfolio"
  name: "portfolio"
  folder: "markdown/portfolio"
  create: true
  fields:
    - {label: "Client", name: "client", widget: "string"}
    - {label: "Description", name: "title", widget: "string"}
    - {label: "Embed Link", name: "embed", widget: "string"}
    - {label: "Still", name: "still", widget: "image"}