backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections: 
- label: "Comedy Albums"
  name: "albums"
  folder: "markdown/albums"
  create: true
  fields:
    - {label: "Title", name: "title", widget: "string"}
    - {label: "thumbnail", name: "thumbnail", widget: "image"}

- label: "Trusted Partners"
  name: "trusted"
  folder: "markdown/trusted"
  create: true
  fields:
    - {label: "Name", name: "name", widget: "string"}
    - {label: "thumbnail", name: "thumbnail", widget: "image"}
